### ISSUE TITLE
Updating to guzzlehttp/guzzle 7

### ISSUE THREAD

**Issue by RodideBoer** [rabobank-nederland/omnikassa-php-sdk#15]
Is there any chance the PHP implementation will be updated to use guzzle version 7?

**Comment by mout-rabobank** [comment]
Hi Rodi, thanks for contacting!
No decision as been made yet as we are currently also considering the option to move to Symfony HTTP client.  I expect that we can give a definite answer in the coming months.

**Comment by RodideBoer** [comment]
Ok, thanks for answering. We will keep an eye on it. Moving to Symfony HTTP client would be great too I guess.

**Comment by harmputman** [comment]
Any chance there is an update regarding this issue? Usage of Guzzle 6 prevents us from using this package atm.

Updating HTTP client package (whether it's Guzzle 7 or Symfony HTTP) would be greatly appreciated!

**Comment by mout-rabobank** [comment]
Thanks for the heads up. I will check and get back to you as soon as possible.

**Comment by mrk-j** [comment]
Any news on this?
