### ISSUE TITLE
 Fatal error: Uncaught GuzzleHttp\Ring\Exception\ConnectException: cURL error 6

### ISSUE THREAD

**Issue by Lionsiek** [rabobank-nederland/omnikassa-php-sdk#9]
Hello, I have an issue with making transactions with certain amounts(37.91 and 68.57, EUR), in an older version of your SDK, this was an issue with the rounding of numbers and is fixed in the newer versions, but when I updated our entire SDK, I got an error which states " **_Fatal error: Uncaught GuzzleHttp\Ring\Exception\ConnectException: cURL error 6: Could not resolve host: gatekeeper;_**".
So I ended up updating only the part that rounds the total price of the transaction, but when this is done, it takes those 2 amounts, adds 1 cent and creates the transaction, which results in the amount to be paid ends up being 37.92 or 68.58.
Do you current solution for these problems?

**Comment by mout-rabobank** [comment]
Hi @Lionsiek , sorry for the late response. My suggestion would be to first check how we can get your code working with the latest SDK. I tried to reproduce it, but I did not get the ConnectException with cURL error 6: Could not resolve host: gatekeeper.
Can you please share your code that creates an Endpoint instance and specifically which value you supply as the $baseURL parameter when calling the static createInstance() method of Endpoint?

**Comment by mout-rabobank** [comment]
Hi @Lionsiek , we have released a new version of the PHP SDK that contains a fix for the rounding problem that you reported on July 1st. It is available in Packagist (https://packagist.org/packages/rabobank/omnikassa-sdk#v1.12.1).
